### ISSUE TITLE
Support NEW LINE 

### ISSUE THREAD

**Issue by afshin-ir** [JoeJoeTV/kdeconnectapplet#2]
Hello.
"Send SMS" dose not support new line in "Message" field when I want to insert new line. 
I will thankful if you support this features. 

![image](https://user-images.githubusercontent.com/14938202/114578179-ed475c80-9c91-11eb-99dc-895cc4760381.png)

**Comment by JoeJoeTV** [comment]
I'm sorry that I am just answering after more than a year, but the main version of this applet is located in the applets repository for Linux Mint (https://github.com/linuxmint/cinnamon-spices-applets/tree/master/kdecapplet@joejoetv). I haven't found an easy way to push commits both to the main applets repo and this one, since the folder structure is different, so I mostly develop on the applets repo.
I'm currently in the process of rewriting the applet for changes in KDE Connect aswell as to provide more features and configurability.
I will look at fixing this issue, but it may now be easier to just use the KDE Connect SMS app.

**Comment by JoeJoeTV** [comment]
Ok, I just checked and you already posted that issue on the applets repo, so I'm just going to close this. Thanks for reporting anyways!
